/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gestion_Libros;

import Controlador.TLista_Gestion_Libros;
import Entidades.BILIOTECA;


/**
 *
 * @author maldo
 */
public class frmInicio_Biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio_Biblioteca
     */
    public frmInicio_Biblioteca() {
        initComponents();
        setLocationRelativeTo(null);
        CargarDatos();
        Datos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1_____INGRESAR______ = new javax.swing.JButton();
        jButton2______ELIMINAR______ = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1______BUSCAR______ = new javax.swing.JButton();
        jButton2______MODIFICAR______ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("REGISTROS DE LIBROS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1_____INGRESAR______.setText("INGRESAR");
        jButton1_____INGRESAR______.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_____INGRESAR______ActionPerformed(evt);
            }
        });

        jButton2______ELIMINAR______.setText("ELIMINAR");
        jButton2______ELIMINAR______.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2______ELIMINAR______ActionPerformed(evt);
            }
        });

        jButton1______BUSCAR______.setText("BUSCAR");
        jButton1______BUSCAR______.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1______BUSCAR______ActionPerformed(evt);
            }
        });

        jButton2______MODIFICAR______.setText("MODIFICAR");
        jButton2______MODIFICAR______.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2______MODIFICAR______ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1______BUSCAR______))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1_____INGRESAR______)
                                .addGap(214, 214, 214)
                                .addComponent(jButton2______MODIFICAR______)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2______ELIMINAR______)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1______BUSCAR______))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_____INGRESAR______)
                    .addComponent(jButton2______ELIMINAR______)
                    .addComponent(jButton2______MODIFICAR______))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    BILIOTECA op;
    TLista_Gestion_Libros OP2;

    public static void CargarDatos() {
        jTable1.setModel(TLista_Gestion_Libros.Visualizar_Libros_Registrados());
    }

    public void Datos() {
        TLista_Gestion_Libros.Insertar_Libro(op = new BILIOTECA(1, "ALICIA EL PAÍS DE LAS MARAVILLAS", "DANIEL NOBOA", "TERROR", "ECUADOT LTCS"));
        TLista_Gestion_Libros.Insertar_Libro(op = new BILIOTECA(2, "LOS 3 CERDITOS ", "PATO DONALD", "PARA NIÑOS", "FIFA"));
        TLista_Gestion_Libros.Insertar_Libro(op = new BILIOTECA(3, "SCOOBY DOO", "WILL SMITH", "COMEDIA", "Warner Bros."));
        TLista_Gestion_Libros.Insertar_Libro(op = new BILIOTECA(4, "SPIDER-VERSE", "POST MALONE", "COMEDIA", "Marvel"));
        CargarDatos();
    }

    private void jButton1_____INGRESAR______ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_____INGRESAR______ActionPerformed
        // TODO add your handling code here:

        Edit_Registros frm = new Edit_Registros();
        frm.setVisible(true);
        CargarDatos();


    }//GEN-LAST:event_jButton1_____INGRESAR______ActionPerformed

    private void jButton2______ELIMINAR______ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2______ELIMINAR______ActionPerformed
        // TODO add your handling code here:

        int Fila_Seleccionada = jTable1.getSelectedRow();

        if (Fila_Seleccionada >= 0) {
            TLista_Gestion_Libros.RegistrarLibros.remove(Fila_Seleccionada);
            CargarDatos();
        }

    }//GEN-LAST:event_jButton2______ELIMINAR______ActionPerformed

    private void jButton2______MODIFICAR______ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2______MODIFICAR______ActionPerformed
        // TODO add your handling code here:

        if (jTable1.getSelectedRow() >= 0) {
            String cod = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            int pos = TLista_Gestion_Libros.Buscar(cod);

            if(pos >= 0){
                frmModificar_Libro frm = new frmModificar_Libro();
                frm.SetDatos(TLista_Gestion_Libros.RegistrarLibros.get(pos));
                frm.setVisible(true);
            }

        }


    }//GEN-LAST:event_jButton2______MODIFICAR______ActionPerformed

    private void jButton1______BUSCAR______ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1______BUSCAR______ActionPerformed
        // TODO add your handling code here:
        
        String bus = jTextField1.getText();
        jTable1.setModel(TLista_Gestion_Libros.Visualizar_Libros_Registrados(bus));
        
    }//GEN-LAST:event_jButton1______BUSCAR______ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio_Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_____INGRESAR______;
    private javax.swing.JButton jButton1______BUSCAR______;
    private javax.swing.JButton jButton2______ELIMINAR______;
    private javax.swing.JButton jButton2______MODIFICAR______;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
